Repository aditya-bhaumik/Pathsphere, pull requests merged in 2024-10, with the labels that each got.

#10 add responsiveness to the page
  styles.css
Labels: gssoc-ext, level 2

#25 Added the Footer Section with Icons and Responsiveness
  forum.html
  index.html
  jobs.html
  scholarships.html
  styles.css
Labels: gssoc-ext, level 2

#30 Devx mani < added pathsphere as a home navigation >
  forum.html
  index.html
  jobs.html
  scholarships.html
  styles.css
Labels: gssoc-ext, level 1

#48 Logo and icons
  P (1).png
  faqs.html
  ficon.png
  forum.html
  index.html
  jicon.png
  jobs.html
  scholarships.html
  sicon.png
  styles.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#58 Added :: Expandable and Collapsible FAQs (closes Issue #51)
  index.html
  script.js
  styles.css
Labels: gssoc-ext, level 1

#65 added forum page
  forum.html
  styles.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#67 Improve scholarship and job sections with enhanced features
  jobs.html
  scholarships.html
Labels: gssoc-ext, level 3, hacktoberfest-accepted, level updated

#76 Added dark mode to all the pages(issue #66)
  blog.html
  faqs.html
  forum.html
  jobs.html
  scholarships.html
  script.js
  styles.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#83 Added Favicon
  blog.html
  faqs.html
  forum.html
  images/pathsphere.png
  index.html
  jobs.html
  scholarships.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#103 Scholarship cards Updates Issue Resolved #92
  scholarships.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#102 Bhattrai
  index.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#119 Added CSS styles for job listing #55
  jobs.css
  jobs.html
  jobs.js
  styles.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#117 Card Font Updated(#113)
  styles.css
Labels: gssoc-ext, level 1

#180 scroll up button added
  index.html
  styles.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#181 solved issue #178
  jobs.css
  jobs.html
  scholarships.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#147 Fixed the Dark-Mode Visibility in FAQ Section/Page (issue#146)
  faqs.css
  faqs.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#159 Add Code Of Conduct
  CODE_OF_CONDUCT.md
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#198 solved issue #191
  blog.html
  faqs.html
  forum.html
  index.html
  jobs.css
  jobs.html
  scholarships.html
  script.js
  styles.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted, approved

#110 issue no 62 : added about page
  about.css
  about.html
  blog.html
  faqs.html
  forum.html
  images/team1.png
  images/team2.png
  images/team3.jpeg
  images/team4.jpeg
  index.html
  jobs.html
  scholarships.html
  styles.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#211 adding animation effect in social media icons
  about.html
  forum.html
  index.html
  jobs.html
  scholarships.html
  styles.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#200 adding hover effect to cards of home page
  styles.css
Labels: gssoc-ext, level 1

#268 FIXED THE RESPONSIVENESS ON EVERY PAGE
  blog.html
  contact.html
  faqs.css
  faqs.html
  forum.html
  jobs.css
  jobs.html
  scholarships.html
  script.js
  styles.css
Labels: gssoc-ext, level 2

#235 solved the issue of dark mode text invisiblity issue#229
  styles.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted, level updated

#275 Add Hover Effect to Toggle Mode
  .hintrc
  styles.css
Labels: good first issue, gssoc-ext, level 1, hacktoberfest-accepted

#295 Update README.md
  README.md
Labels: documentation, gssoc-ext, level 1, hacktoberfest-accepted

#307 solved issue #289
  blog.html
  faqs.html
  forum.html
  index.html
  jobs.html
  scholarships.html
  styles.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#344 Expected Behavior for Footer Section: #329
  scholarships.html
  styles.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#349 Refactor navigation links and add FAQs page
  index.html
  styles.css
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#368 fixed newsletter subscription button functionality
  pages/blog/blog.css
  pages/blog/blog.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#346 Added Tech Stack in README.md
  README.md
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#355 added website visitors widget #354
  components/Footer/Footer.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#403 accordion added
  index.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#384 Add detailed section(read more) to scholarship cards
  pages/scholarships/scholarships.css
  pages/scholarships/scholarships.html
  pages/scholarships/scholarships.js
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#430 FAQ
  pages/faqs/faqs.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#501 ✨Chatbot added✨
  index.html
  pages/about/about.html
  pages/blog/blog.html
  pages/contact/contact.html
  pages/faqs/faqs.html
  pages/forum/forum.html
  pages/jobs/jobs.html
  pages/scholarships/scholarships.html
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#553 Update forum.html
  pages/forum/forum.html
Labels: good first issue, gssoc-ext, level 1, hacktoberfest-accepted

#645 enhanced scholarship cards
  pages/scholarship-feature/scholarships.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#654 ADD Roadmap section on README
  README.md
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#663 copywrite year is dynamic now
  components/Footer/Footer.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#678 Successfully make faq, job and forum page responsive for small screen sizes.
  pages/faqs/faqs.css
  pages/jobs/jobs.css
  styles/styles.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#691 feat: styled community discussion section with responsive cards
  pages/forum/forum.css
  pages/forum/forum.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#703 added privacy policy page
  components/Footer/Footer.html
  pages/privacypolicy/privacypolicy.css
  pages/privacypolicy/privacypolicy.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#708 added social sharing option
  components/Footer/Footer.html
  styles/styles.css
Labels: good first issue, gssoc-ext, level 2, hacktoberfest-accepted

#707 FAQ heading is now visible in every type of device.
  pages/faqs/faqs.css
  pages/faqs/faqs.html
Labels: good first issue, gssoc-ext, level 1, hacktoberfest-accepted

#721 Adding Effects to "Welcome to PathSphere"
  styles/styles.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#714 Done adding visit links for all Blogs
  pages/blog/blog.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#746 Resume Builder functionality #660
  index.html
  pages/resume-builder/resume.css
  pages/resume-builder/resume.html
  pages/resume-builder/resume.js
  styles/styles.css
Labels: gssoc-ext, level 3, hacktoberfest-accepted

#772 added paging to scholarships
  pages/scholarship-feature/scholarships.css
  pages/scholarship-feature/scholarships.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#787 Implement GitHub PR Issue Checker Workflow
  .github/workflows/pr-checker.yml
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#797 🛠️FIX : Sign Up page - Name field validation
  pages/login-signup/login-signup.html
Labels: good first issue, gssoc-ext, level 1, hacktoberfest-accepted

#815 Added Successful msg Upon Registering
  pages/login-signup/login-signup.css
  pages/login-signup/login-signup.html
  pages/login-signup/login-signup.js
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#833 Successful mailId format checker
  pages/blog/blog.js
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#844 Added Icon in TitleBar !!
  favicon.ico
  images/favicon.ico
  logo.png
  pages/favicon.ico
  pages/scholarship-feature/scholarships.html
  pages/scholarships/favicon.ico
  pathsphere.png
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#870 Update README.md with table of contents
  README.md
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#881 fix/navigate to home page after successful login
  components/Navbar/Navbar.html
  components/Navbar/Navbar.js
  pages/login-signup/login-signup.js
Labels: good first issue, gssoc-ext, level 2, hacktoberfest-accepted

#877 Redesign cards on landing page
  images/account.png
  images/feedback-testimonial-icon.png
  index.html
  styles/styles.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#856 fix: Fixed FAQ active state
  pages/faqs/faqs.js
Labels: good first issue, gssoc-ext, level 1, hacktoberfest-accepted

#888 Fixes:#886- Jashwanth/localrun_error
  .vscode/settings.json
  components/Footer/Footer.html
  components/GlobalScripts/GlobalScripts.html
  components/LoadingScreen/LoadingScreen.html
  components/Navbar/Navbar.html
  components/Navbar/Navbar.js
  components/ScrollToTop/ScrollToTop.html
  index.html
  pages/blog/blog.html
  pages/contact/contact.html
  pages/contributor/index.html
  pages/faqs/faqs.html
  pages/forum/forum.html
  pages/jobs/jobs.html
  pages/login-signup/login-signup.html
  pages/login-signup/login-signup.js
  pages/privacypolicy/privacypolicy.html
  pages/resume-builder/resume.html
  pages/scholarship-feature/scholarships.html
  pages/scholarships/scholarships.html
  pages/terms/index.html
  scripts/componentLoader.js
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#910 created Own Blog Page
  components/Navbar/Navbar.html
  pages/blog/blog.html
  pages/blog/write_your_blog.html
Labels: good first issue, gssoc-ext, level 2, hacktoberfest-accepted

#969 Changing Backgrounds to Scholarship Page for Improved User Experience
  pages/scholarship-feature/scholarships.css
  pages/scholarship-feature/scholarships.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#984 add button like google and facbook
  pages/login-signup/login-signup.css
  pages/login-signup/login-signup.html
Labels: good first issue, gssoc-ext, level 2, hacktoberfest-accepted, level updated

#975 Enhancements and Corrections to PathSphere README.md
  README.md
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1005 Aligned the items of the forum
  index.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1007 [UI] Redesign of blogs section
  pages/blog/blog.css
  pages/blog/blog.html
Labels: gssoc-ext, level 3, hacktoberfest-accepted, level updated

#1013 Enhanced FAQ Section and Homepage Alignment Fixes
  index.html
  pages/faqs/faqs.css
  pages/faqs/faqs.html
Labels: gssoc-ext, level 3, hacktoberfest-accepted, level updated

#1022 Add Location Maps to Contact Us Page
  pages/contact/contact.css
  pages/contact/contact.html
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1032 Fix Button Sizing and Text Readability in Sponsorship Page Cards
  pages/scholarship-feature/scholarships.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1037 Redesign the theme swicther toogle & fix the ui after dark mode
  .DS_Store
  components/.DS_Store
  components/Navbar/Navbar.html
  components/Navbar/Navbar.js
  pages/.DS_Store
  pages/contributor/.DS_Store
  pages/forum/.DS_Store
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1038 Add contact form validation and update error message
  pages/contact/contact.css
  pages/contact/contact.html
  pages/contact/contact.js
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1054 🛠️Fix :Carousel Images Appear Diminished/Lessened, Affecting Visual Quality
  pages/jobs/jobs2.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1056 Enhanced navbar for mobile view
  components/Navbar/Navbar.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1062 text color changed
  pages/scholarship-feature/scholarships.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1051 Updated Readme.md file
  README.md
Labels: documentation, gssoc-ext, level 1, hacktoberfest-accepted

#1072 Issue #944 Navigating issue even if the user is logged in to website
  pages/login-signup/login-signup.html
  pages/login-signup/login-signup.js
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1086 Add a pop up dialog box for subscribing to newsletter done !
  index.html
  popup.jpg
  popup.js
Labels: gssoc-ext, level 3, hacktoberfest-accepted, level updated

#1082 Enhanced the input boxes
  pages/login-signup/login-signup.css
  pages/login-signup/login-signup.js
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1092 improve social media icons
  components/Footer/Footer.html
  styles/styles.css
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1093 I have designed a nicer and better search bar
  pages/jobs/jobs.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1102 #1064 Alignment Issues and Footer Design Improvements Needed
  components/Footer/Footer.html
  styles/styles.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1095 Change Background color on Dark Mode
  pages/forum/forum.html
  pages/jobs/jobs.html
  pages/jobs/jobs2.css
  styles/styles.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1106 Feat: password validation feature upgraded
  pages/login-signup/login-signup.js
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1114 update nav style
  components/Navbar/Navbar.html
  index.html
  styles/styles.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted, level reduced

#1134 bug : Fixes the visibility issue in forum section
  pages/forum/forum.css
  styles/styles.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted
