Repository aditya-bhaumik/Pathsphere, pull requests merged in 2024-11, with the labels that each got.

#1137 #1065 Text Visibility Issue in Scholarship Options
  styles/styles.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1139 Resolve issue of scholarship section
  pages/scholarship-feature/scholarships.css
  pages/scholarship-feature/scholarships.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1156 TEXT IS INVISIBLE IN THE DARK MODE(fixes #1109)
  styles/styles.css
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1153 Added new logo to header and footer !!!
  components/Footer/Footer.html
  components/Navbar/Navbar.html
  images/abcd.png
Labels: gssoc-ext, level 2, hacktoberfest-accepted

#1166 Enhanced ScrollTop Button Functionality
  components/ScrollToTop/ScrollToTop.html
Labels: gssoc-ext, level 1, hacktoberfest-accepted

#1187 Day/night icon issue solved.
  components/Navbar/Navbar.html
  components/Navbar/Navbar.js
  images/initialpng.png
  images/moon.png
  images/sun.png
Labels: gssoc-ext, level 1

#1188 Added Active State Indicator for Navbar
  components/Navbar/Navbar.html
  components/Navbar/Navbar.js
Labels: gssoc-ext, level 2

#1193 Fix 404 Page Redirection for Invalid Routes
  .htaccess
  404.html
Labels: gssoc-ext, level 2
